using System.Collections.Generic;
using System.Linq;
using HVIP.Models;

namespace HVIP.Helpers
{
    public static class ProductCatalog
    {
        private static readonly List<Category> _categories = new List<Category>
        {
            new Category { Id=1, Name="Dilutions",            Slug="dilutions",           Icon="fas fa-flask",                Color="#1b5e20", Description="Classical homeopathic dilutions in various potencies" },
            new Category { Id=2, Name="Mother Tinctures",     Slug="mother-tinctures",    Icon="fas fa-tint",                 Color="#2e7d32", Description="Plant-based mother tinctures (Q potency)" },
            new Category { Id=3, Name="Biochemic Tablets",    Slug="biochemic-tablets",   Icon="fas fa-tablets",              Color="#00695c", Description="12 tissue salts for biochemic therapy" },
            new Category { Id=4, Name="Combination Remedies", Slug="combination",         Icon="fas fa-capsules",             Color="#0277bd", Description="Multi-ingredient drops for specific ailments" },
            new Category { Id=5, Name="Ointments & Creams",   Slug="ointments-creams",    Icon="fas fa-fill-drip",            Color="#e65100", Description="Topical homeopathic preparations" },
            new Category { Id=6, Name="Hair Care",            Slug="hair-care",           Icon="fas fa-spa",                  Color="#4e342e", Description="Arnica-based hair care products" },
            new Category { Id=7, Name="Skin Care",            Slug="skin-care",           Icon="fas fa-leaf",                 Color="#880e4f", Description="Natural skin care solutions" },
            new Category { Id=8, Name="Drops & Syrups",       Slug="drops-syrups",        Icon="fas fa-prescription-bottle",  Color="#4a148c", Description="Liquid homeopathic preparations" },
        };

        private static readonly List<Product> _products = new List<Product>
        {
            // ─── DILUTIONS ─────────────────────────────────────────────────────────
            new Product { Id=1,  Name="Aconite Napellus 30C",      ShortDescription="For sudden fever, anxiety & shock",             Description="Indicated for sudden onset after exposure to cold wind. Effective for high fever, intense fear, restlessness and acute anxiety attacks.",                                               Price=85m,  OriginalPrice=100m, CategoryId=1, CategoryName="Dilutions",            CategoryIcon="fas fa-flask",                CategoryColor="#1b5e20", Brand="HVIP", Stock=150, IsFeatured=true,  IsBestseller=true,  Rating=4.5, ReviewCount=128, Size="30ml" },
            new Product { Id=2,  Name="Arnica Montana 30C",         ShortDescription="For bruises, injuries & muscle soreness",       Description="The most widely used homeopathic remedy for trauma, bruising and muscle soreness. Excellent after physical exertion, falls and surgery.",                                        Price=90m,  OriginalPrice=110m, CategoryId=1, CategoryName="Dilutions",            CategoryIcon="fas fa-flask",                CategoryColor="#1b5e20", Brand="HVIP", Stock=200, IsFeatured=true,  IsBestseller=false, Rating=4.7, ReviewCount=245, Size="30ml" },
            new Product { Id=3,  Name="Belladonna 30C",             ShortDescription="For sudden high fever with redness",            Description="Prescribed for sudden violent fever with flushed face, throbbing headache, extreme sensitivity to light and dryness.",                                                          Price=80m,  OriginalPrice=null, CategoryId=1, CategoryName="Dilutions",            CategoryIcon="fas fa-flask",                CategoryColor="#1b5e20", Brand="HVIP", Stock=175, IsFeatured=false, IsBestseller=true,  Rating=4.3, ReviewCount=89,  Size="30ml" },
            new Product { Id=4,  Name="Calcarea Carb 200C",         ShortDescription="Constitutional remedy for slow metabolism",      Description="Deep constitutional remedy for obesity, profuse sweating of the head, delayed developmental milestones and weak bones in children.",                                             Price=95m,  OriginalPrice=115m, CategoryId=1, CategoryName="Dilutions",            CategoryIcon="fas fa-flask",                CategoryColor="#1b5e20", Brand="HVIP", Stock=120, IsFeatured=true,  IsBestseller=false, Rating=4.6, ReviewCount=156, Size="30ml" },
            new Product { Id=5,  Name="Nux Vomica 30C",             ShortDescription="For digestive disorders & irritability",         Description="Indicated for digestive troubles from overeating, constipation, irritability and over-sensitivity to external stimuli.",                                                       Price=80m,  OriginalPrice=null, CategoryId=1, CategoryName="Dilutions",            CategoryIcon="fas fa-flask",                CategoryColor="#1b5e20", Brand="HVIP", Stock=190, IsFeatured=false, IsBestseller=true,  Rating=4.4, ReviewCount=112, Size="30ml" },
            new Product { Id=6,  Name="Pulsatilla 30C",             ShortDescription="For changeable symptoms, mild temperament",      Description="A polychrest remedy for weeping tendency, changeable symptoms and conditions aggravated by warmth and improved in open air.",                                                  Price=85m,  OriginalPrice=null, CategoryId=1, CategoryName="Dilutions",            CategoryIcon="fas fa-flask",                CategoryColor="#1b5e20", Brand="HVIP", Stock=165, IsFeatured=false, IsBestseller=false, Rating=4.2, ReviewCount=74,  Size="30ml" },
            new Product { Id=7,  Name="Rhus Tox 30C",               ShortDescription="For joint pain worse in cold damp weather",      Description="The leading remedy for joint stiffness and pain that is worse on first motion but improves with continued movement. Excellent for arthritis.",                                  Price=85m,  OriginalPrice=100m, CategoryId=1, CategoryName="Dilutions",            CategoryIcon="fas fa-flask",                CategoryColor="#1b5e20", Brand="HVIP", Stock=210, IsFeatured=true,  IsBestseller=false, Rating=4.5, ReviewCount=198, Size="30ml" },

            // ─── MOTHER TINCTURES ──────────────────────────────────────────────────
            new Product { Id=8,  Name="Calendula Officinalis Q",    ShortDescription="Wound healing & antiseptic",                    Description="A powerful antiseptic and wound healer. Used internally and topically for cuts, wounds, ulcers and skin infections. Promotes rapid granulation.",                                Price=150m, OriginalPrice=180m, CategoryId=2, CategoryName="Mother Tinctures",     CategoryIcon="fas fa-tint",                 CategoryColor="#2e7d32", Brand="HVIP", Stock=140, IsFeatured=true,  IsBestseller=true,  Rating=4.8, ReviewCount=312, Size="30ml" },
            new Product { Id=9,  Name="Echinacea Purpurea Q",       ShortDescription="Immunity booster, anti-infective",              Description="Widely used to boost immune system function and fight infections. Effective for recurring colds, flu and low-grade fevers.",                                                  Price=180m, OriginalPrice=null, CategoryId=2, CategoryName="Mother Tinctures",     CategoryIcon="fas fa-tint",                 CategoryColor="#2e7d32", Brand="HVIP", Stock=125, IsFeatured=false, IsBestseller=false, Rating=4.5, ReviewCount=87,  Size="30ml" },
            new Product { Id=10, Name="Thuja Occidentalis Q",        ShortDescription="For warts, skin growths & polyps",              Description="Used for warts, condylomata, polyps and skin growths. Also effective for vaccination-related complaints and sycotic conditions.",                                             Price=160m, OriginalPrice=200m, CategoryId=2, CategoryName="Mother Tinctures",     CategoryIcon="fas fa-tint",                 CategoryColor="#2e7d32", Brand="HVIP", Stock=100, IsFeatured=true,  IsBestseller=false, Rating=4.3, ReviewCount=65,  Size="30ml" },
            new Product { Id=11, Name="Berberis Vulgaris Q",         ShortDescription="Kidney stones & urinary complaints",            Description="Primary remedy for kidney stones, renal colic and urinary tract issues with radiating burning pain.",                                                                        Price=170m, OriginalPrice=null, CategoryId=2, CategoryName="Mother Tinctures",     CategoryIcon="fas fa-tint",                 CategoryColor="#2e7d32", Brand="HVIP", Stock=145, IsFeatured=false, IsBestseller=true,  Rating=4.6, ReviewCount=143, Size="30ml" },

            // ─── BIOCHEMIC TABLETS ─────────────────────────────────────────────────
            new Product { Id=12, Name="Ferrum Phosphoricum 6X",      ShortDescription="First stage of inflammation & fever",           Description="First aid biochemic salt for early stages of inflammation, fever and infections. Supports oxygen transport in the blood.",                                                    Price=95m,  OriginalPrice=null, CategoryId=3, CategoryName="Biochemic Tablets",    CategoryIcon="fas fa-tablets",              CategoryColor="#00695c", Brand="HVIP", Stock=230, IsFeatured=false, IsBestseller=true,  Rating=4.4, ReviewCount=178, Size="25g"  },
            new Product { Id=13, Name="Kali Phosphoricum 6X",         ShortDescription="Nerve tonic for mental fatigue",                Description="The nerve tissue salt for nervous exhaustion, mental fatigue, anxiety, depression and poor memory. Essential for students and professionals.",                                Price=95m,  OriginalPrice=null, CategoryId=3, CategoryName="Biochemic Tablets",    CategoryIcon="fas fa-tablets",              CategoryColor="#00695c", Brand="HVIP", Stock=195, IsFeatured=true,  IsBestseller=false, Rating=4.6, ReviewCount=134, Size="25g"  },
            new Product { Id=14, Name="Magnesia Phosphorica 6X",      ShortDescription="Cramps, spasms & neuralgic pain",               Description="The antispasmodic biochemic salt. Used for muscle cramps, menstrual cramps, colic and shooting neuralgic pains relieved by heat.",                                          Price=90m,  OriginalPrice=110m, CategoryId=3, CategoryName="Biochemic Tablets",    CategoryIcon="fas fa-tablets",              CategoryColor="#00695c", Brand="HVIP", Stock=180, IsFeatured=true,  IsBestseller=false, Rating=4.5, ReviewCount=96,  Size="25g"  },
            new Product { Id=15, Name="Natrum Muriaticum 6X",          ShortDescription="Water balance & dry mucous membranes",          Description="Regulates body fluids. Used for headaches, cold sores, dry skin and hay fever with watery discharge.",                                                                       Price=95m,  OriginalPrice=null, CategoryId=3, CategoryName="Biochemic Tablets",    CategoryIcon="fas fa-tablets",              CategoryColor="#00695c", Brand="HVIP", Stock=210, IsFeatured=false, IsBestseller=false, Rating=4.3, ReviewCount=67,  Size="25g"  },
            new Product { Id=16, Name="Calcarea Phosphorica 6X",       ShortDescription="Bone health & growing pains",                   Description="Strengthens bones and teeth, aids calcium absorption. Used for growing pains, delayed teething and fracture healing.",                                                       Price=90m,  OriginalPrice=null, CategoryId=3, CategoryName="Biochemic Tablets",    CategoryIcon="fas fa-tablets",              CategoryColor="#00695c", Brand="HVIP", Stock=165, IsFeatured=false, IsBestseller=false, Rating=4.2, ReviewCount=54,  Size="25g"  },

            // ─── COMBINATION REMEDIES ──────────────────────────────────────────────
            new Product { Id=17, Name="HVIP Febin Drops",             ShortDescription="For cold, cough and mild fever",                Description="A combination remedy for common cold, cough, runny nose and mild fever. Safe and effective for adults and children above 2 years.",                                         Price=120m, OriginalPrice=145m, CategoryId=4, CategoryName="Combination Remedies", CategoryIcon="fas fa-capsules",             CategoryColor="#0277bd", Brand="HVIP", Stock=320, IsFeatured=true,  IsBestseller=true,  Rating=4.6, ReviewCount=267, Size="30ml" },
            new Product { Id=18, Name="HVIP Stresswin Drops",          ShortDescription="For stress, anxiety & sleeplessness",           Description="Helps manage stress, anxiety, nervous tension and insomnia. A safe, non-habit forming natural remedy for modern lifestyle stress.",                                          Price=135m, OriginalPrice=null, CategoryId=4, CategoryName="Combination Remedies", CategoryIcon="fas fa-capsules",             CategoryColor="#0277bd", Brand="HVIP", Stock=215, IsFeatured=false, IsBestseller=true,  Rating=4.7, ReviewCount=198, Size="30ml" },
            new Product { Id=19, Name="HVIP Diabonil Drops",           ShortDescription="Blood sugar management support",                Description="Supports healthy blood sugar levels as a complementary treatment for type 2 diabetes management. Contains Syzygium, Gymnema and other key remedies.",                       Price=140m, OriginalPrice=165m, CategoryId=4, CategoryName="Combination Remedies", CategoryIcon="fas fa-capsules",             CategoryColor="#0277bd", Brand="HVIP", Stock=180, IsFeatured=true,  IsBestseller=false, Rating=4.4, ReviewCount=123, Size="30ml" },

            // ─── OINTMENTS & CREAMS ────────────────────────────────────────────────
            new Product { Id=20, Name="HVIP Calendula Ointment",       ShortDescription="Antiseptic cream for cuts & wounds",            Description="Natural antiseptic preparation promoting wound healing. Excellent for cuts, abrasions, burns and skin irritations. Soothes and repairs.",                                    Price=130m, OriginalPrice=155m, CategoryId=5, CategoryName="Ointments & Creams",   CategoryIcon="fas fa-fill-drip",            CategoryColor="#e65100", Brand="HVIP", Stock=145, IsFeatured=false, IsBestseller=true,  Rating=4.7, ReviewCount=289, Size="25g"  },
            new Product { Id=21, Name="HVIP Arnica Ointment",           ShortDescription="For bruises, sprains & muscle pain",            Description="Provides relief from bruises, sprains, muscle soreness and joint pains. An essential first-aid ointment for every home.",                                                  Price=125m, OriginalPrice=null, CategoryId=5, CategoryName="Ointments & Creams",   CategoryIcon="fas fa-fill-drip",            CategoryColor="#e65100", Brand="HVIP", Stock=190, IsFeatured=true,  IsBestseller=false, Rating=4.5, ReviewCount=176, Size="25g"  },
            new Product { Id=22, Name="HVIP Clear Face Cream",          ShortDescription="Homeopathic acne & pimple control cream",        Description="With Calendula and Thuja, helps clear acne, pimples and blemishes. Reduces oiliness and improves skin texture. Suitable for oily skin.",                                 Price=195m, OriginalPrice=220m, CategoryId=5, CategoryName="Ointments & Creams",   CategoryIcon="fas fa-fill-drip",            CategoryColor="#e65100", Brand="HVIP", Stock=250, IsFeatured=true,  IsBestseller=true,  Rating=4.8, ReviewCount=412, Size="25g"  },

            // ─── HAIR CARE ─────────────────────────────────────────────────────────
            new Product { Id=23, Name="HVIP Arnica Hair Oil",           ShortDescription="Prevents hair fall, promotes growth",           Description="Arnica Montana Hair Oil with essential nutrients reduces hair fall, promotes growth, prevents premature greying and nourishes the scalp.",                                  Price=210m, OriginalPrice=250m, CategoryId=6, CategoryName="Hair Care",            CategoryIcon="fas fa-spa",                  CategoryColor="#4e342e", Brand="HVIP", Stock=310, IsFeatured=true,  IsBestseller=true,  Rating=4.9, ReviewCount=523, Size="100ml", IsNew=true  },
            new Product { Id=24, Name="HVIP Hair Vitalizer",             ShortDescription="Scalp nourishment & dandruff control",          Description="Nourishes the scalp, strengthens hair roots and prevents dandruff. Contains Arnica, Thuja, Cantharis and other botanical extracts.",                                    Price=285m, OriginalPrice=320m, CategoryId=6, CategoryName="Hair Care",            CategoryIcon="fas fa-spa",                  CategoryColor="#4e342e", Brand="HVIP", Stock=195, IsFeatured=false, IsBestseller=true,  Rating=4.6, ReviewCount=287, Size="100ml" },
            new Product { Id=25, Name="HVIP Arnica Shampoo",             ShortDescription="Gentle cleansing, reduces hair fall",           Description="Arnica-enriched herbal shampoo for daily use. Cleanses without stripping natural oils, reduces hair fall and promotes lustrous hair.",                                   Price=175m, OriginalPrice=210m, CategoryId=6, CategoryName="Hair Care",            CategoryIcon="fas fa-spa",                  CategoryColor="#4e342e", Brand="HVIP", Stock=220, IsFeatured=false, IsBestseller=false, Rating=4.4, ReviewCount=165, Size="200ml" },

            // ─── SKIN CARE ─────────────────────────────────────────────────────────
            new Product { Id=26, Name="HVIP Aloe Vera Gel",             ShortDescription="Soothing moisturizer for all skin types",        Description="Aloe Vera Gel with homeopathic extracts provides deep moisture, soothes sunburn and helps heal skin irritations and minor wounds.",                                     Price=175m, OriginalPrice=null, CategoryId=7, CategoryName="Skin Care",            CategoryIcon="fas fa-leaf",                 CategoryColor="#880e4f", Brand="HVIP", Stock=275, IsFeatured=true,  IsBestseller=false, Rating=4.5, ReviewCount=163, Size="150ml", IsNew=true  },
            new Product { Id=27, Name="HVIP Sunscreen SPF30",            ShortDescription="UV protection with natural ingredients",         Description="Broad-spectrum SPF30 sunscreen with Calendula and Berberis. Protects from UVA/UVB while nourishing the skin naturally.",                                                Price=220m, OriginalPrice=265m, CategoryId=7, CategoryName="Skin Care",            CategoryIcon="fas fa-leaf",                 CategoryColor="#880e4f", Brand="HVIP", Stock=190, IsFeatured=true,  IsBestseller=false, Rating=4.3, ReviewCount=98,  Size="50ml"  },

            // ─── DROPS & SYRUPS ────────────────────────────────────────────────────
            new Product { Id=28, Name="HVIP Ocudrops Eye Drops",         ShortDescription="For eye fatigue, redness & irritation",         Description="Provides relief from digital eye strain, redness, irritation and dryness. Safe for regular use by screen users.",                                                        Price=115m, OriginalPrice=null, CategoryId=8, CategoryName="Drops & Syrups",       CategoryIcon="fas fa-prescription-bottle",  CategoryColor="#4a148c", Brand="HVIP", Stock=155, IsFeatured=false, IsBestseller=false, Rating=4.4, ReviewCount=112, Size="10ml"  },
            new Product { Id=29, Name="HVIP Immunoboost Syrup",           ShortDescription="Builds immunity, prevents infections",          Description="Strengthens the immune system, helps prevent recurring infections and improves overall vitality. Contains Echinacea, Baptisia and key immune-supportive remedies.",      Price=150m, OriginalPrice=175m, CategoryId=8, CategoryName="Drops & Syrups",       CategoryIcon="fas fa-prescription-bottle",  CategoryColor="#4a148c", Brand="HVIP", Stock=230, IsFeatured=true,  IsBestseller=true,  Rating=4.7, ReviewCount=345, Size="100ml" },
            new Product { Id=30, Name="HVIP Digyton Drops",               ShortDescription="For indigestion, bloating & acidity",           Description="Treats indigestion, flatulence, bloating and gastric discomfort. A comprehensive digestive formula with Nux Vomica, Carbo Veg and Lycopodium.",                       Price=125m, OriginalPrice=145m, CategoryId=8, CategoryName="Drops & Syrups",       CategoryIcon="fas fa-prescription-bottle",  CategoryColor="#4a148c", Brand="HVIP", Stock=180, IsFeatured=true,  IsBestseller=false, Rating=4.5, ReviewCount=187, Size="30ml"  },
            new Product { Id=31, Name="HVIP Sleepzyme Drops",             ShortDescription="Natural sleep aid, no side effects",            Description="Promotes restful sleep naturally. Contains Coffea Cruda, Passiflora and Valeriana for safe, effective sleep support without dependency.",                               Price=135m, OriginalPrice=null, CategoryId=8, CategoryName="Drops & Syrups",       CategoryIcon="fas fa-prescription-bottle",  CategoryColor="#4a148c", Brand="HVIP", Stock=165, IsFeatured=false, IsBestseller=false, Rating=4.6, ReviewCount=134, Size="30ml",  IsNew=true  },
        };

        public static List<Category> GetCategories() => new List<Category>(_categories);
        public static Category GetCategory(int id) => _categories.FirstOrDefault(c => c.Id == id);

        public static List<Product> GetAll() => new List<Product>(_products);
        public static Product GetById(int id) => _products.FirstOrDefault(p => p.Id == id);

        public static List<Product> GetFeatured(int count = 8) =>
            _products.Where(p => p.IsFeatured).Take(count).ToList();

        public static List<Product> GetBestsellers(int count = 6) =>
            _products.Where(p => p.IsBestseller).Take(count).ToList();

        public static List<Product> GetNewArrivals(int count = 4) =>
            _products.Where(p => p.IsNew).Take(count).ToList();

        public static List<Product> GetByCategory(int categoryId) =>
            _products.Where(p => p.CategoryId == categoryId).ToList();

        public static List<Product> GetRelated(int productId, int categoryId, int count = 4) =>
            _products.Where(p => p.CategoryId == categoryId && p.Id != productId).Take(count).ToList();
    }
}
